-- ============================================================================
-- partner_pipeline seed — Days 6–7 discovery sweep (2026-06-01)
-- 43 enriched candidates: 10 re-verified Prospect Intel + 33 newly swept.
-- All at voice_fit >= 3 (doctrine bar). Conflicts flagged inline in why_fit
-- as [CONFLICT: none / soft / hard / unknown — reason]. The Days 8–9 ranking
-- task demotes hard-conflict rows to status='passed' during the top-25 cut.
-- Paste into: https://supabase.com/dashboard/project/jwhjysjvehqslzcfpehl/sql/new
-- ============================================================================

insert into partner_pipeline
  (name, surface, handle, motion, archetype, audience_est, voice_fit,
   status, contact_path, why_fit, source_agent, next_action, next_action_date)
values
-- ── Group A: 10 re-verified Prospect Intel candidates (source: dossier) ──
('Neil Bhuiyan','podcast','happyselling.io/podcast; X @HappySelling_io','affiliate','creator',NULL,4,'enriched','happyselling.io contact; X DM @HappySelling_io','First-2yr SDR interview format — exact ICP overlap. [CONFLICT: none — clean, only fully-clean re-verify]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Florin Tatulea','newsletter','salesflo.substack.com; X @FlorinTatulea','affiliate','creator',12000,5,'enriched','salesflo.substack.com / thesalesflo.com; X DM','Tactical SDR/AE prospecting, operator-direct, anti-fluff. [CONFLICT: soft — Head of Sales Dev at Common Room, vendor not a course]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Stefan Conic','skool','skool.com/sdr-hire-community-1422; sdrhire.com','affiliate','community',42,3,'enriched','sdrhire.com contact','SDR career/skills community + podcast. [CONFLICT: soft — paid Skool courses overlap AESDR curriculum]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Daniel Goerner','skool','skool.com/sdr-bdr-community-7025','affiliate','community',NULL,3,'enriched','Skool DM @daniel-goerner','Coaches SDRs cold-call to AE, ICP aligned. [CONFLICT: hard — paid coaching + launching competing mastery courses (changed since May)]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Elric Legloire','newsletter','newsletter.outbound.kitchen; X @elriclegloire','affiliate','creator',7000,4,'enriched','newsletter.outbound.kitchen/chat; X DM @elriclegloire','Outbound systems, operator voice (skews slightly senior). [CONFLICT: soft — paywalled Outbound Chef Kit, adjacent]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Jed Mahrle','newsletter','content.practicalprospecting.io; jed.substack.com','affiliate','creator',NULL,5,'enriched','content.practicalprospecting.io contact','Cold-email/outbound tactics, plain operator voice. [CONFLICT: soft — runs done-for-you outbound agency, service not course]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Tom Slocum','newsletter','thesdlab.beehiiv.com (now The GTM Launchpad); X @Tommy_Slocum','affiliate','coach',NULL,4,'enriched','thesdlab.com contact; X DM @Tommy_Slocum','Hands-on outbound coaching, no-fluff. [CONFLICT: hard — sells Outbound Accelerator 8-12wk program (changed since May)]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Sam Nelson','newsletter','samnelson.substack.com; X @realSamNelson','affiliate','creator',NULL,4,'enriched','samnelson.substack.com; X DM @realSamNelson','Agoge sequence / outbound, known operator voice. [CONFLICT: hard — founder of Agoge Prospecting School, paid SDR training (changed since May)]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Collin Mitchell','podcast','X @collinmitchell; Sales Transformation podcast','affiliate','creator',NULL,3,'enriched','X DM @collinmitchell','Broad sales/AI content, medium SDR fit. [CONFLICT: soft — Head of Sales at Humantic AI vendor; ALSO activity unverified for 2026, confirm still hosting]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),
('Michael Gagliano','community','sdrnation.com; X @SDRNationHQ','affiliate','community',NULL,4,'enriched','sdrnation.com/apply-now','Affordable SDR/BDR training community, ICP-aligned. [CONFLICT: hard — SDR Nation x JB Sales training-vendor partnership (changed since May)]','dossier','Rank for top-25 cut (Days 8-9)',current_date+2),

-- ── Group B: Sweep 1 — Skool communities (source: scout) ──
('Lukas Arellano','skool','skool.com/break-into-corporate-sales','affiliate','coach',695,4,'enriched','Skool DM; about-page owner contact','Helps land first BDR/SDR roles; anti-credential peer tone. [CONFLICT: none found — verify no paid-course upsell]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Aaron Reeves','skool','skool.com/b2b-sales-university-5171','affiliate','coach',1400,4,'enriched','Skool DM @aaron-reeves-9793; Calendly on community','Outbound systems for SaaS reps, weekly Q and A, operator-direct. [CONFLICT: soft — sells outbound consulting services, not a rival course]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Kekoa MacAuley','skool','skool.com/the-modern-sdr-5692; themodernsdr.com','affiliate','coach',168,3,'enriched','Skool DM @kekoa-macauley-3093','SDR program + free community, relevant audience. [CONFLICT: hard — paid The Modern SDR program, direct competitor]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Erik Fisher','skool','skool.com/elevate-sales-academy; elevatesalestraining.io','affiliate','coach',37,3,'enriched','Skool DM @erik-fisher-4395','B2B AE program, 19-yr vet operator. [CONFLICT: hard — paid AE program; also skews AE not first-1-2-yr]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Norman Rodriguez','skool','skool.com/elevate-careers','affiliate','community',49,3,'enriched','Skool DM @norman-rodriguez-1805','Break-into-tech-sales, mission-driven (wealth-gap focus). [CONFLICT: hard — state-licensed paid SDR bootcamp]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Modern Day Sales (owner UNVERIFIED)','skool','skool.com/modern-day-sales-free-7463','affiliate','coach',NULL,4,'enriched','Skool DM via community','Best voice match found: SDR-to-Presidents-Club-Year-1-AE framing, exact buyer + tone. [CONFLICT: unknown — has paid Modern Day Outbound course; VERIFY OWNER NAME before any outreach]','scout','Verify owner identity, then rank',current_date+2),

-- ── Group C: Sweep 2 — newsletters + podcasts (source: scout) ──
('Nic Conley','newsletter','jointhefollowup.com','affiliate','creator',10000,4,'enriched','Reply-to on any issue; site contact','Ex-AE, twice-weekly tactical breakdowns for IC SDRs/AEs, peer tone. [CONFLICT: none found]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Cooper Krauss','newsletter','dailysalesrep.substack.com','affiliate','creator',NULL,4,'enriched','Substack reply-to','Working rep breaks down cold-call anatomy, sequences, SDR-to-AE. [CONFLICT: soft — runs a $9/mo community]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Tajh Walker','newsletter','coldcallingchronicles.substack.com','affiliate','creator',NULL,5,'enriched','Substack reply-to','Ex-enterprise SDR, prospecting frameworks, harsh-truth operator tone, no hype. [CONFLICT: none]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Stacy Tan','newsletter','weeklyroundtable.substack.com','affiliate','alumni',NULL,5,'enriched','Substack reply-to','Built a startup 0-to-acquisition; runs 30/60/90 new-AE ramp + discovery series — exact ICP. [CONFLICT: none]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Jesse Woodbury','podcast','salesplayers.com','affiliate','creator',NULL,4,'enriched','Guest/contact form on salesplayers.com','Operator host, early-stage startup SaaS selling, host-read fit. [CONFLICT: soft-flag — guest roster includes course-sellers, verify no competing sponsor]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Eric Smith','podcast','The Lowly SDR (Buzzsprout 1030501)','affiliate','community',NULL,5,'enriched','Buzzsprout episode page / show contact','By-an-SDR-for-SDRs, raw peer conversations, anti-guru, squarely on-audience. [CONFLICT: none — verify still publishing]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Nick Bontrager','podcast','The Promotable SDR (Libsyn)','affiliate','alumni',NULL,5,'enriched','Libsyn show contact / guest pitch','Interviews only ex-SDRs who got promoted — exact promotion-path narrative AESDR sells. [CONFLICT: none]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Will Barron','podcast','salesman.com/sales-podcasts','affiliate','coach',NULL,3,'enriched','Guest application form on salesman.com','Big reach (1M+ downloads claimed), repeatable-system framing. [CONFLICT: hard — Salesman.com sells its own sales academy/membership]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Scott Ingram','podcast','top1.fm','affiliate','coach',NULL,3,'enriched','Guest form on top1.fm','Quota-carrying host interviewing top-1% ICs; skews enterprise-veteran. [CONFLICT: soft — runs Sales Success Community]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Leslie Venetz','newsletter','salesledgtm.com; TikTok @salestipstok','affiliate','coach',NULL,3,'enriched','Newsletter reply-to / salesledgtm.com contact','Outbound operator (250k+ cold calls), earn-the-right ethos, anti-spam. [CONFLICT: hard — Sales-Led GTM agency + paid training + book. Appeared in both Sweep 2 + 3, merged]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Eric Finch (Higher Levels)','podcast','higherlevels.com','affiliate','coach',NULL,3,'enriched','Show contact via higherlevels.com','Break-into / level-up tech-sales, exact audience. [CONFLICT: hard — Higher Levels sells Tech Sales Ascension SDR/AE courses]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Lori Richardson','podcast','womensalespros.com','affiliate','community',NULL,3,'enriched','Guest contact via womensalespros.com','Community host, reaches early-career women in sales dev, diversifies sourcing. [CONFLICT: soft — community/advisory, verify no competing sponsor]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('School of SDR','newsletter','schoolofsdr.substack.com; schoolofsdr.com','affiliate','community',NULL,3,'enriched','Substack reply-to / schoolofsdr.com contact','Strong early-career SDR content + community (India-market focus). [CONFLICT: hard — School of SDR IS a paid SDR training program]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),

-- ── Group D: Sweep 3 — practitioner-network figures (source: scout) ──
('Will Aitken','youtube','youtube.com/@justwillaitken; willaitken.com','affiliate','creator',50000,4,'enriched','Contact form at willaitken.com','Practitioner video coach, demos real cold email/calls, low-guru. [CONFLICT: light — sells own courses/merch, no full competing curriculum]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Kyle Asay','creator','salesintroverts.com; x.com/KyleAsay_','affiliate','coach',10000,5,'enriched','salesintroverts.com contact / X DM','Ex-SDR to VP, concrete AE daily-execution frameworks, anti-hype. [CONFLICT: hard — SalesIntroverts sells AE courses]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Giulio Segantini','community','underdogsales.com','affiliate','coach',4000,4,'enriched','underdogsales.com contact / IG DM','Operator cold-call trainer, real-call teardowns, anti-guru tone. [CONFLICT: hard — sells Cold Calling course + $99/mo academy]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Troy Barter','creator','practicalprospecting.io; sellbetter.xyz/show-speakers/troy-barter','affiliate','creator',NULL,4,'enriched','practicalprospecting.io contact','Raw no-fluff outbound execution, ex-SDR who rose ranks. [CONFLICT: hard — SalesOrg.io / Practical Prospecting paid training]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Sara Uy','creator','The Career Collective podcast; SellingSara','affiliate','creator',NULL,5,'enriched','The Career Collective pod / SellingSara site','Built audience posting live cold calls as a working SDR, peer-built ethos. [CONFLICT: low — early-stage coaching, scope unverified]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Vin Matano','creator','x.com/vinmatano; youtube.com/@vinmatano','affiliate','creator',NULL,4,'enriched','X DM / Creatorbuzz site','Ex-top SDR/AE, teaches real cold-email/video frameworks. [CONFLICT: soft — EvaBot advisor, vendor sponsorship tie]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Gabrielle Blackwell','newsletter','gabrielleblackwell.gumroad.com; Workweek newsletter','affiliate','community',NULL,5,'enriched','Gumroad / newsletter reply','SDR-manager voice, real 1:1 + dev tactics, peer-built not guru. [CONFLICT: none — newsletter + digital products, no full course]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Sarah Brazier','creator','dimmo.ai; sellbetter.xyz/show-speakers/sarah-brazier','affiliate','creator',NULL,4,'enriched','Dimmo site / podcast','Built brand new-SDR to AE at Gong, authentic seller story. [CONFLICT: soft — co-founder of Dimmo, a SaaS vendor]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Marcus Chan','coach','venliconsulting.com','affiliate','coach',NULL,3,'enriched','venliconsulting.com contact','WSJ-bestselling author, Fortune-500 operator background (polished/guru-leaning). [CONFLICT: hard — Venli 6-Figure Sales Academy, direct competing course]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Charlotte Johnson','creator','sellbetter.xyz/show-speakers/charlotte-johnson','affiliate','creator',NULL,5,'enriched','Via 30MPC / newsletter signup (low-confidence path)','Working-rep voice, jargon-free real outreach teardowns. [CONFLICT: none found]','scout','Confirm contact path, then rank',current_date+2),
('Kevin Dorsey','community','salesleadershipaccelerator.com; skool.com/@kevin-dorsey-2954','affiliate','coach',NULL,3,'enriched','SLA site contact / Skool DM','Deep operator (built $100M orgs), but leadership-tier + heavy self-brand. [CONFLICT: hard — Sales Leadership Accelerator paid community]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Samantha McKenna','coach','samsalesconsulting.com','affiliate','coach',NULL,3,'enriched','samsalesconsulting.com contact','#samsales Show-Me-You-Know-Me methodology, strong credibility but exec-tilt. [CONFLICT: hard — sells #samsales cadences/courses]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Ashleigh Early','podcast','theothersideofsales (podcast/community)','affiliate','community',NULL,4,'enriched','Podcast site contact form','Practitioner-built, inclusive, anti-bro-culture, real-work focus. [CONFLICT: maybe — does sales coaching/consulting, competing scope unverified]','scout','Rank for top-25 cut (Days 8-9)',current_date+2),
('Mark Kosoglow','creator','sellbetter.xyz; via 30MPC','affiliate','creator',NULL,4,'enriched','Via 30MPC / own site (low-confidence path)','Built Outreach 0 to $250M, concrete systems teacher, operator-direct. [CONFLICT: maybe — tied to 30MPC ecosystem which sells courses]','scout','Confirm contact path, then rank',current_date+2);

-- Verify after running:  select count(*) from partner_pipeline;   -> expect 43
-- Then:  select voice_fit, count(*) from partner_pipeline group by voice_fit order by voice_fit desc;
